apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.application}}
  namespace: {{.Values.branch}}
  labels:
    app: {{.Values.application}}
    version: "{{.Values.application}}-{{.Values.commit}}"
spec:
  replicas: {{.Values.scale}}
  template:
    metadata:
      labels:
        app: {{.Values.application}}
    spec:
      containers:
      - name: {{.Values.application}}
        image: "amitkshirsagar13/{{.Values.application}}:{{.Values.commit}}"
        ports:
        - containerPort: 8989
        env:
        - name: VHOSTNAME
          value: "{{.Values.application}}.{{.Values.branch}}.shinigami.io"
        - name: VCONFIGHOST
          value: kube-eureka
        - name: VEUREKAHOST
          value: kube-eureka
        - name: VCONFIGPORT
          value: "8761"
        - name: VEUREKAPORT
          value: "8761"
        - name: VSECUREPORT
          value: "443"
        - name: VNONSECUREPORT
          value: "80"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.application}}
  namespace: {{.Values.branch}}
spec:
  ports:
  - port: 8089
    targetPort: 8989
  selector:
    app: {{.Values.application}}
