apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/tls-acme: "true"
  name: "{{.Values.application}}.{{.Values.branch}}"
  namespace: {{.Values.branch}}
  labels:
    version: "{{.Values.application}}-{{.Values.commit}}"
spec:
  tls:
  - hosts:
    - "{{.Values.application}}.{{.Values.branch}}.shinigami.io"
  - secretName: {{.Values.branch}}
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: "{{.Values.application}}.{{.Values.branch}}.shinigami.io"
      http:
        paths:
          - backend:
              serviceName: {{.Values.application}}
              servicePort: 8089
            path: /
