---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.alpha.kubernetes.io/storage-class: default
  name: grafana-pvc-01
  namespace: monitoring
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "6Gi"
