---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: XNAME
  namespace: XNAMESPACE
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: XNAME
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: XNAME
    namespace: XNAMESPACE
