apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/tls-acme: "true"
  name: kira
  namespace: dev
  labels:
    version: kira-server-{{.Values.commit}}
spec:
  tls:
  - hosts:
    - kira.dev.shinigami.io
  - secretName: dev
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: kira.{{.Values.branch}}.shinigami.io
      http:
        paths:
          - backend:
              serviceName: kira-server
              servicePort: 8988
            path: /
