apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/tls-acme: "true"
  name: default.nginx
  namespace: kube-system
spec:
  tls:
  - hosts:
    - kubedash.kube-system.shinigami.io
  - secretName: tls-cert
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: kubedash.kube-system.shinigami.io
      http:
        paths:
          - backend:
              serviceName: kubernetes-dashboard
              servicePort: 80
            path: /
