apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.application}}
  namespace: {{.Values.branch}}
  labels:
    app: {{.Values.application}}
    version: "{{.Values.application}}-{{.Values.commit}}"
    hystrix.cluster: default
    hystrix.enabled: "true"
spec:
  replicas: {{.Values.scale}}
  template:
    metadata:
      labels:
        app: {{.Values.application}}
        hystrix.cluster: default
        hystrix.enabled: "true"
    spec:
      hostAliases:
       - ip: 127.0.0.1
         hostnames:
         - {{.Values.application}}
         - "{{.Values.application}}.{{.Values.branch}}.shinigami.io"
      containers:
      - name: {{.Values.application}}
        image: "amitkshirsagar13/{{.Values.application}}:{{.Values.commit}}"
        ports:
        - containerPort: 8080
        env:
        - name: spring.profiles.active
          value: "{{.Values.profile}}"
        - name: VHOSTNAME
          value: "{{.Values.application}}.{{.Values.branch}}.shinigami.io"
        - name: VPORT
          value: "8080"
        - name: VEUREKAHOST
          value: kube-eureka
        - name: VEUREKAPORT
          value: "8761"
        - name: VSERVICEHOST
          value: {{.Values.application}}
        - name: VSECUREPORT
          value: "80"
        - name: VNONSECUREPORT
          value: "80"
        - name: VCONFIGHOST
          value: kube-eureka
        - name: VCONFIGPORT
          value: "8761"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.application}}
  namespace: {{.Values.branch}}
  hystrix.cluster: default
  hystrix.enabled: "true"
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: {{.Values.application}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/tls-acme: "true"
  name: "{{.Values.application}}.{{.Values.branch}}"
  namespace: {{.Values.branch}}
  labels:
    version: "{{.Values.application}}-{{.Values.commit}}"
spec:
  tls:
  - hosts:
    - "{{.Values.application}}.{{.Values.branch}}.shinigami.io"
  - secretName: {{.Values.branch}}
  backend:
    serviceName: default-http-backend
    servicePort: 80
  rules:
    - host: "{{.Values.application}}.{{.Values.branch}}.shinigami.io"
      http:
        paths:
          - backend:
              serviceName: {{.Values.application}}
              servicePort: 80
            path: /
