---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-persistent-storage
  namespace: jenkins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/jenkins"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-persistent-storage-claim
  namespace: jenkins
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
