apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-server
spec:
  template:
    metadata:
      lables:
        app: demo-server
    spec:
      containers:
      - name: demo-server
        image: gcr.io/basekub/demo-server:{{ .Values.commit}}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-server
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-server
