apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simple-server
spec:
  template:
    metadata:
      lables:
        app: simple-server
    spec:
      containers:
      - name: simple-server
        image: yeasy/simple-web:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-server
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demo-server
